import type { Metadata } from 'next'
import { League_Spartan, Roboto, } from 'next/font/google'
import './globals.css'

const roboto = Roboto({
	subsets: ['latin'],
	weight: ["400", "500", "700",],
	variable: "--font-Roboto"

})

const leagueSpartan = League_Spartan({
	subsets: ["latin"],
	weight: ["400", "500", "600", "700"],
	variable: "--font-League_Spartan"
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${roboto.variable} ${leagueSpartan.variable} bg-white bg-no-repeat`}>{children}</body>
		</html>
	)
}
